language: c++

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl > /dev/null
  - haxelib install lime > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install actuate > /dev/null
  - haxelib install box2d > /dev/null
  - haxelib install swf > /dev/null
  - haxelib install layout > /dev/null
  - haxelib install format > /dev/null
  - haxelib dev openfl-samples $(pwd)

script:
  - haxelib run openfl build $(pwd)/ActuateExample flash
  - haxelib run openfl build $(pwd)/AddingAnimation flash
  - haxelib run openfl build $(pwd)/AddingText flash
  - haxelib run openfl build $(pwd)/BunnyMark neko
  - haxelib run openfl build $(pwd)/DisplayingABitmap flash
  - haxelib run openfl build $(pwd)/HandlingKeyboardEvents flash
  - haxelib run openfl build $(pwd)/HandlingMouseEvents flash
  - haxelib run openfl build $(pwd)/HerokuShaders linux
  - haxelib run openfl build $(pwd)/PiratePig flash
  - haxelib run openfl build $(pwd)/PlayingSound flash
  - haxelib run openfl build $(pwd)/SimpleBox2D flash
  - haxelib run openfl build $(pwd)/SimpleOpenGLView linux
  - haxelib run openfl build $(pwd)/SimpleSWFLayout flash

notifications:
  slack: openfl:ba3HbgtZflW8TNcJEQ1B4tAY
